set(_CATKIN_CURRENT_PACKAGE "v2_movebase")
set(v2_movebase_VERSION "0.0.0")
set(v2_movebase_MAINTAINER "ashmitha <ashmitha@todo.todo>")
set(v2_movebase_PACKAGE_FORMAT "2")
set(v2_movebase_BUILD_DEPENDS )
set(v2_movebase_BUILD_EXPORT_DEPENDS )
set(v2_movebase_BUILDTOOL_DEPENDS "catkin")
set(v2_movebase_BUILDTOOL_EXPORT_DEPENDS )
set(v2_movebase_EXEC_DEPENDS )
set(v2_movebase_RUN_DEPENDS )
set(v2_movebase_TEST_DEPENDS )
set(v2_movebase_DOC_DEPENDS )
set(v2_movebase_URL_WEBSITE "")
set(v2_movebase_URL_BUGTRACKER "")
set(v2_movebase_URL_REPOSITORY "")
set(v2_movebase_DEPRECATED "")